### ISSUE TITLE
"gem install hitimes -v '1.2.2'" fails on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by tomasbjerre** [guzmo/xyz-docker-dev-api#4]
$ bundle install
Updating https://github.com/mitchellh/vagrant-spec.git
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Using rake 10.4.2
Using addressable 2.3.7
Using builder 3.2.2
Using bundler 1.7.13

Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

```
    /usr/bin/ruby1.9.1 extconf.rb 
```

/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from extconf.rb:2:in `<main>'

Gem files will remain installed in /tmp/bundler20150326-21825-17wjo17/hitimes-1.2.2/gems/hitimes-1.2.2 for inspection.
Results logged to /tmp/bundler20150326-21825-17wjo17/hitimes-1.2.2/gems/hitimes-1.2.2/ext/hitimes/c/gem_make.out
An error occurred while installing hitimes (1.2.2), and Bundler cannot continue.
Make sure that `gem install hitimes -v '1.2.2'` succeeds before bundling.

**Comment by guzmo** [comment]
did you solve this?

**Comment by tomasbjerre** [comment]
Yes =)

**Comment by guzmo** [comment]
How? :) if someone get the same error : P

**Comment by tomasbjerre** [comment]
I got it when following the "old" README.md on installation.

I think the new changes in README.md solves the issue. It now makes it clear that you simple need to install and setup Docker. And not fiddle with Vagrant if you use Ubuntu.
